// Build script: generates manifest.json from shared sources.
// Run via: node dist/manifest-gen.js (after tsc compiles everything to dist/)

import fs from "fs";
import path from "path";
import { urlPatterns } from "./sites";
import { pluginSettings } from "./settings";

const manifest = {
  _generated:
    "This file is auto-generated by manifest-gen.ts. Do not edit directly.",
  name: "gallery-dl",
  version: "2.1.0",
  description:
    "Download images and media from Pixiv, Instagram, DeviantArt, Danbooru, " +
    "ExHentai, Patreon, Kemono, and 400+ other sites using gallery-dl",
  author: "TheArchiver",
  urlPatterns,
  settings: pluginSettings,
  viewProvider: {
    viewId: "gallery-dl-browser",
    label: "Gallery Browser",
    icon: "Image",
    entryPoint: "view/index.js",
  },
};

const outPath = path.resolve(__dirname, "..", "manifest.json");
fs.writeFileSync(outPath, JSON.stringify(manifest, null, 2) + "\n");
console.log(
  `Generated manifest.json with ${urlPatterns.length} URL patterns and ${pluginSettings.length} settings`
);
