// Build script: generates manifest.json from shared sources.
// Run via: node dist/manifest-gen.js (after tsc compiles everything to dist/)

import fs from "fs";
import path from "path";
import { urlPatterns } from "./sites";
import { pluginSettings } from "./settings";

const manifest = {
  _generated:
    "This file is auto-generated by manifest-gen.ts. Do not edit directly.",
  name: "yt-dlp",
  version: "1.0.0",
  description:
    "Download video and audio from YouTube, Twitch, TikTok, Vimeo, SoundCloud, and 1800+ other sites using yt-dlp",
  author: "TheArchiver",
  urlPatterns,
  settings: pluginSettings,
};

const outPath = path.resolve(__dirname, "..", "manifest.json");
fs.writeFileSync(outPath, JSON.stringify(manifest, null, 2) + "\n");
console.log(`Generated manifest.json with ${urlPatterns.length} URL patterns and ${pluginSettings.length} settings`);
